server:
  port: 8787

spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

spring-doc:
  packagesToScan: fr.kata.order.delivery
  api-docs:
    path: /api-docs
